### ISSUE TITLE
Auto Rename Tag not work on Vue Language Features (Volar)

### ISSUE THREAD

**Issue by meiliujun** [BroJenuel/CodeExtensionPack#2]
uninstall Vue Language Features (Volar) and install Auto Rename Tag can work in *.vue

**Comment by BroJenuel** [comment]
can you check if the auto tag extension on your vs code is enabled?

**Comment by meiliujun** [comment]
This problem may be caused by volar. After I uninstall volar, Auto Rename Tag works normally.
Now I use vuter instead of volar, and auto rename tag is OK

**Comment by BroJenuel** [comment]
The auto tag extension works really fine on other users, I dont know how it doesnt work on your end. Their might be a problem on your vs code configuration :)
